# Generated by Django 3.0.5 on 2020-05-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20200524_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poetry',
        ),
    ]
