# Generated by Django 3.0.5 on 2020-06-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0004_delete_poetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaylistName', models.CharField(max_length=100)),
                ('Link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('DateCompleted', models.DateTimeField(null=True)),
                ('Favourite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
