# Generated by Django 3.0.5 on 2020-05-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='Testi',
            new_name='Message',
        ),
    ]
